apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaspnetcoreapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myaspnetcoreapp
  template:
    metadata:
      labels:
        app: myaspnetcoreapp
    spec:
      containers:
      - name: myaspnetcoreapp
        image: syddselin/myaspnetcoreapp:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80