name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'  

      - name: Install dependencies
        run: dotnet restore MyAspNetCoreApp.csproj  # Adjust the path if necessary

      - name: Build
        run: dotnet build MyAspNetCoreApp.csproj --no-restore  # Adjust the path if necessary

      - name: Test
        run: dotnet test MyAspNetCoreApp.csproj --no-build --verbosity normal  # Adjust the path if necessary

      - name: Build Docker image
        run: |
          docker build -t myaspnetcoreapp .  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Push Docker image
        run: |
          docker tag myaspnetcoreapp:latest syddselin/myaspnetcoreapp:latest  
          docker push syddselin/myaspnetcoreapp:latest
